# Generated by Django 4.1.7 on 2023-09-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_owneranduser_status_and_more'),
        ('master', '0011_alter_status_created_at_alter_usertype_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_store', to='user.owneranduser')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_store', to='master.status')),
            ],
        ),
    ]
