# Generated by Django 4.1.7 on 2023-09-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_owneranduser_status_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('item_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_tablespace': 'user_item_test_space',
            },
        ),
        migrations.AddIndex(
            model_name='userstore',
            index=models.Index(fields=['store_name'], name='store_name'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_item_owner', to='user.owneranduser'),
        ),
        migrations.AddIndex(
            model_name='useritem',
            index=models.Index(fields=['item_name'], name='item_name'),
        ),
    ]
