# Generated by Django 4.1.7 on 2023-09-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_owneranduser_status_and_more'),
        ('store', '0002_useritem_userstore_store_name_useritem_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('tag_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tag_owner', to='user.owneranduser')),
            ],
            options={
                'db_tablespace': 'user_tag_test_space',
            },
        ),
        migrations.AddIndex(
            model_name='usertag',
            index=models.Index(fields=['tag_name'], name='store_usert_tag_nam_1ec3bb_idx'),
        ),
    ]
