# Generated by Django 4.1.7 on 2023-10-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_alter_status_created_at_alter_usertype_created_at_and_more'),
        ('store', '0005_itemcategory_useritem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='category',
            field=models.ManyToManyField(through='store.ItemCategory', to='master.category'),
        ),
    ]
