# Generated by Django 4.1.7 on 2023-10-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_owneranduser_status_and_more'),
        ('order', '0002_remove_cart_deleted_remove_cart_deleted_by_cascade_and_more'),
        ('store', '0006_alter_useritem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='customer_cart',
            field=models.ManyToManyField(through='order.Cart', to='user.customer'),
        ),
    ]
