# Generated by Django 4.1.7 on 2023-10-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_useritem_customer_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.useritem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userstore')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
