# Generated by Django 4.1.7 on 2023-10-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_itemstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='store',
            field=models.ManyToManyField(through='store.ItemStore', to='store.userstore'),
        ),
    ]
