# Generated by Django 4.1.7 on 2023-10-15 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_itemstore_created_at_alter_itemstore_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 15, 23, 21, 32, 353821)),
            preserve_default=False,
        ),
    ]
