# Generated by Django 4.1.7 on 2023-09-03 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
