# Generated by Django 4.1.7 on 2023-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['module_name', 'status_int'], name='status_rel'),
        ),
    ]
