# Generated by Django 4.1.7 on 2023-09-03 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_status_status_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 15, 23, 18, 174206, tzinfo=datetime.timezone.utc)),
        ),
    ]
