# Generated by Django 4.1.7 on 2023-09-03 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_status_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 17, 14, 14, 589040, tzinfo=datetime.timezone.utc)),
        ),
    ]
