# Generated by Django 4.1.7 on 2023-09-10 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_status_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 12, 3, 55, 469524, tzinfo=datetime.timezone.utc)),
        ),
    ]
