# Generated by Django 4.1.7 on 2023-09-28 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_alter_category_category_name_alter_status_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 10, 42, 4, 97387, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 10, 42, 4, 97387, tzinfo=datetime.timezone.utc)),
        ),
    ]
