# Generated by Django 4.1.7 on 2023-09-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
