# Generated by Django 4.1.7 on 2023-09-10 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_status_created_at'),
        ('user', '0003_owneranduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneranduser',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.status'),
        ),
        migrations.AlterField(
            model_name='owneranduser',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.usertype'),
        ),
    ]
