# Generated by Django 4.1.7 on 2023-10-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_cart_deleted_remove_cart_deleted_by_cascade_and_more'),
        ('store', '0007_useritem_customer_cart'),
        ('user', '0004_alter_owneranduser_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='item_cart',
            field=models.ManyToManyField(through='order.Cart', to='store.useritem'),
        ),
    ]
