# Generated by Django 4.1.7 on 2023-10-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0019_alter_status_created_at_alter_usertype_created_at_and_more'),
        ('user', '0004_alter_owneranduser_status_and_more'),
        ('store', '0006_alter_useritem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_customer', to='user.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_item', to='store.useritem')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_status', to='master.status')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
