# Generated by Django 4.1.7 on 2023-10-10 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_alter_status_created_at_alter_usertype_created_at'),
        ('store', '0006_alter_useritem_category'),
        ('user', '0004_alter_owneranduser_status_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='deleted_by_cascade',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_customer', to='user.customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='store.useritem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_status', to='master.status'),
        ),
    ]
