# Generated by Django 4.1.7 on 2023-10-10 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_alter_status_created_at_alter_usertype_created_at'),
        ('order', '0003_cart_deleted_cart_deleted_by_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='cart_status', to='master.status'),
        ),
    ]
