# Generated by Django 4.1.7 on 2023-10-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_useritem_customer_cart'),
        ('master', '0024_alter_status_created_at_alter_usertype_created_at'),
        ('user', '0005_customer_item_cart'),
        ('order', '0004_alter_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_detail_item', to='store.useritem')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('checkout_code', models.CharField(max_length=100, unique=True)),
                ('rate', models.IntegerField(blank=True, default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_customer', to='user.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_status', to='master.status')),
                ('user_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_user_store', to='store.userstore')),
            ],
            options={
                'ordering': ['created_at'],
                'db_tablespace': 'order_checkout',
            },
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['customer', 'user_store_id'], name='order_check_custome_fba527_idx'),
        ),
    ]
