# Generated by Django 4.1.7 on 2023-10-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0025_paymentstatus_alter_status_created_at_and_more'),
        ('order', '0005_checkoutdetail_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_payment_method', to='master.paymentmethod'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.paymentstatus'),
        ),
    ]
