# Generated by Django 4.1.7 on 2023-10-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_alter_bank_updated_at_alter_category_updated_at_and_more'),
        ('order', '0006_checkout_payment_method_checkout_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_payment_method', to='master.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.paymentstatus'),
        ),
    ]
