# Generated by Django 4.1.7 on 2023-10-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_alter_status_created_at_alter_usertype_created_at'),
        ('order', '0007_alter_checkout_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='master.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_status', to='master.status'),
        ),
    ]
