# Generated by Django 4.1.7 on 2023-10-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_checkout_checkout_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='rate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
