# Generated by Django 4.1.7 on 2023-10-22 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_checkout_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetail',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detail_checkout', to='order.checkout'),
            preserve_default=False,
        ),
    ]
